# Project Details 
AWS_Region: 'us-east-1'
devopsProfile: 'DevRole'
AWS-Account: '478634282923.dkr.ecr.us-east-1.amazonaws.com'

microservices_java:
  services:
    - service: 'DocumentService'
      servicename: 'HIG-EDM-R3U-doc-MS'
      clustername: 'HIG-EDM-R3U-MS-Cluster'
      taskdefname: 'HIG-EDM-R3U-MS-Cluster-doc-TD'
    - service: 'RuleEngineService'
      servicename: 'HIG-EDM-R3U-rule-MS'
      clustername: 'HIG-EDM-R3U-MS-Cluster'
      taskdefname: 'HIG-EDM-R3U-MS-Cluster-re-TD'
    - service: 'AutoSplitService'
      servicename: 'HIG-EDM-R3U-auto-MS'
      clustername: 'HIG-EDM-R3U-MS-Cluster'
      taskdefname: 'HIG-EDM-R3U-MS-Cluster-aums-TD'
    - service: 'DocConversionService'
      servicename: 'HIG-EDM-R3U-doccon-MS'
      clustername: 'HIG-EDM-R3U-MS-Cluster'
      taskdefname: 'HIG-EDM-R3U-MS-Cluster-dcms-TD'
    - service: 'ExcelExtractionService'
      servicename: 'HIG-EDM-R3U-exlext-MS'
      clustername: 'HIG-EDM-R3U-MS-Cluster'
      taskdefname: 'HIG-EDM-R3U-MS-Cluster-exms-TD'
    - service: 'JavaStructuredExtractionService'
      servicename: 'HIG-EDM-R3U-java-MS'
      clustername: 'HIG-EDM-R3U-MS-Cluster'
      taskdefname: 'HIG-EDM-R3U-MS-Cluster-je-TD'
    - service: 'MergeService'
      servicename: 'HIG-EDM-R3U-merge-MS'
      clustername: 'HIG-EDM-R3U-MS-Cluster'
      taskdefname: 'HIG-EDM-R3U-MS-Cluster-mrg-TD'
    - service: 'SearchEngineService'
      servicename: 'HIG-EDM-R3U-search-MS'
      clustername: 'HIG-EDM-R3U-MS-Cluster'
      taskdefname: 'HIG-EDM-R3U-MS-Cluster-se-TaskDef'
    - service: 'StructuredPostProcessService'
      servicename: 'HIG-EDM-R3U-strpp-MS'
      clustername: 'HIG-EDM-R3U-MS-Cluster'
      taskdefname: 'HIG-EDM-R3U-MS-Cluster-strpp-TD'
    - service: 'TextExtractionService'
      servicename: 'HIG-EDM-R3U-text-MS'
      clustername: 'HIG-EDM-R3U-MS-Cluster'
      taskdefname: 'HIG-EDM-R3U-MS-Cluster-te-TD'
    - service: 'PageIdentificationService'
      servicename: 'HIG-EDM-R3U-pageidn-MS'
      clustername: 'HIG-EDM-R3U-MS-Cluster'
      taskdefname: 'HIG-EDM-R3U-MS-Cluster-pi-TaskDef'
    - service: 'TransformationService'
      servicename: 'HIG-EDM-R3U-tranfm-MS'
      clustername: 'HIG-EDM-R3U-MS-Cluster'
      taskdefname: 'HIG-EDM-R3U-MS-Cluster-trn-TD'
    - service: 'UnstructuredExtractionService'
      servicename: 'HIG-EDM-R3U-unstrext-MS'
      clustername: 'HIG-EDM-R3U-MS-Cluster'
      taskdefname: 'HIG-EDM-R3U-MS-Cluster-unex-TaskDef'
    - service: 'UnstructuredPostProcessService'
      servicename: 'HIG-EDM-R3U-unstrpst-MS'
      clustername: 'HIG-EDM-R3U-MS-Cluster'
      taskdefname: 'HIG-EDM-R3U-MS-Cluster-unpp-TaskDef'
    - service: 'ExcelPostProcessService'
      servicename: 'HIG-EDM-R3U-exlpst-MS'
      clustername: 'HIG-EDM-R3U-MS-Cluster'
      taskdefname: 'HIG-EDM-R3U-MS-Cluster-epms-TD'
    - service: 'AutoSplitOrchestrator'
      servicename: 'HIG-EDM-R3U-auto-ORCH'
      clustername: 'HIG-EDM-R3U-MS-Cluster'
      taskdefname: 'HIG-EDM-R3U-MS-Cluster-auorc-TaskDef'
    - service: 'DocConversionOrchestrator'
      servicename: 'HIG-EDM-R3U-doccon-ORCH'
      clustername: 'HIG-EDM-R3U-MS-Cluster'
      taskdefname: 'HIG-EDM-R3U-MS-Cluster-dcorc-TaskDef'
    - service: 'ExcelExtractionOrchestrator'
      servicename: 'HIG-EDM-R3U-exlext-ORCH'
      clustername: 'HIG-EDM-R3U-MS-Cluster'
      taskdefname: 'HIG-EDM-R3U-MS-Cluster-exorc-TaskDef'
    - service: 'ExcelPostProcessOrchestrator'
      servicename: 'HIG-EDM-R3U-exlpst-ORCH'
      clustername: 'HIG-EDM-R3U-MS-Cluster'
      taskdefname: 'HIG-EDM-R3U-MS-Cluster-eporc-TaskDef'
    - service: 'ExtractionEventGenOrchestrator'
      servicename: 'HIG-EDM-R3U-evntgen-ORCH'
      clustername: 'HIG-EDM-R3U-MS-Cluster'
      taskdefname: 'HIG-EDM-R3U-MS-Cluster-evnt-TaskDef'
    - service: 'L2PageClassificationOrchestrator'
      servicename: 'HIG-EDM-R3U-l2page-ORCH'
      clustername: 'HIG-EDM-R3U-MS-Cluster'
      taskdefname: 'HIG-EDM-R3U-MS-Cluster-l2pg-TaskDef'
    - service: 'MultiConversionOrchestrator'
      servicename: 'HIG-EDM-R3U-mutli-ORCH'
      clustername: 'HIG-EDM-R3U-MS-Cluster'
      taskdefname: 'HIG-EDM-R3U-MS-Cluster-mult-TaskDef'
    - service: 'PageClassificationOrchestrator'
      servicename: 'HIG-EDM-R3U-page-ORCH'
      clustername: 'HIG-EDM-R3U-MS-Cluster'
      taskdefname: 'HIG-EDM-R3U-MS-Cluster-pc-TaskDef'
    - service: 'PreProcessOrchestrator'
      servicename: 'HIG-EDM-R3U-preproc-ORCH'
      clustername: 'HIG-EDM-R3U-MS-Cluster'
      taskdefname: 'HIG-EDM-R3U-MS-Cluster-pp-TaskDef'
    - service: 'StructuredExtractionOrchestrator'
      servicename: 'HIG-EDM-R3U-strex-ORCH'
      clustername: 'HIG-EDM-R3U-MS-Cluster'
      taskdefname: 'HIG-EDM-R3U-MS-Cluster-steorc-TaskDef'
    - service: 'StructuredPostProcessOrchestrator'
      servicename: 'HIG-EDM-R3U-strpst-ORCH'
      clustername: 'HIG-EDM-R3U-MS-Cluster'
      taskdefname: 'HIG-EDM-R3U-MS-Cluster-stporc-TaskDef'
    - service: 'StructuredRequestExtractionOrchestrator'
      servicename: 'HIG-EDM-R3U-strex-ORCH'
      clustername: 'HIG-EDM-R3U-MS-Cluster'
      taskdefname: 'HIG-EDM-R3U-MS-Cluster-steorc-TaskDef'
    - service: 'TextExtractionOrchestrator'
      servicename: 'HIG-EDM-R3U-text-ORCH'
      clustername: 'HIG-EDM-R3U-MS-Cluster'
      taskdefname: 'HIG-EDM-R3U-MS-Cluster-teorc-TaskDef'
    - service: 'UnstructuredExtractionOrchestrator'
      servicename: 'HIG-EDM-R3U-unstrext-ORCH'
      clustername: 'HIG-EDM-R3U-MS-Cluster'
      taskdefname: 'HIG-EDM-R3U-MS-Cluster-uexorc-TaskDef'
    - service: 'UnstructuredPostProcessOrchestrator'
      servicename: 'HIG-EDM-R3U-unstrpst-ORCH'
      clustername: 'HIG-EDM-R3U-MS-Cluster'
      taskdefname: 'HIG-EDM-R3U-MS-Cluster-uporc-TaskDef'
    - service: 'WorkFlowProcessingOrchestrator'
      servicename: 'HIG-EDM-R3U-wrkflw-ORCH'
      clustername: 'HIG-EDM-R3U-MS-Cluster'
      taskdefname: 'HIG-EDM-R3U-MS-Cluster-wrkfl-TaskDef'
    - service: 'FailedTemplateGenOrchestrator'
      servicename: 'HIG-EDM-R3U-failtmp-ORCH'
      clustername: 'HIG-EDM-R3U-MS-Cluster'
      taskdefname: 'HIG-EDM-R3U-MS-Cluster-forch-TaskDef'
    - service: 'TransformationOrchestrator'
      servicename: 'HIG-EDM-R3U-tranfm-ORCH'
      clustername: 'HIG-EDM-R3U-MS-Cluster'
      taskdefname: 'HIG-EDM-R3U-MS-Cluster-forch-TaskDef'
    - service: 'UnstructuredRequestOrchestrator'
      servicename: 'HIG-EDM-R3U-unstrreq-ORCH'
      clustername: 'HIG-EDM-R3U-MS-Cluster'
      taskdefname: 'HIG-EDM-R3U-MS-Cluster-forch-TaskDef'

microservices_python:
  services:
    - service: 'preprocessorlvl1'
      servicename: 'HIG-EDM-R3U-preproc-PYMS'
      clustername: 'HIG-EDM-R3U-PY-Cluster'
      taskdefname: 'HIG-EDM-R3U-PY-Cluster-pp-TD'
    - service: 'structuredclassifier'
      servicename: 'HIG-EDM-R3U-strcl-PYMS'
      clustername: 'HIG-EDM-R3U-PY-Cluster'
      taskdefname: 'HIG-EDM-R3U-PY-Cluster-pysc-TD'
    - service: 'structuredextraction'
      servicename: 'HIG-EDM-R3U-strext-PYMS'
      clustername: 'HIG-EDM-R3U-PY-Cluster'
      taskdefname: 'HIG-EDM-R3U-PY-Cluster-pyse-TD'
    - service: 'textextraction'
      servicename: 'HIG-EDM-R3U-textext-PYMS'
      clustername: 'HIG-EDM-R3U-PY-Cluster'
      taskdefname: 'HIG-EDM-R3U-PY-Cluster-te-MSTaskDef'
    - service: 'SOLR'
      servicename: 'HIG-EDM-R3U-SOLR-S'
      clustername: 'HIG-EDM-R3U-SOLR-Cluster'
      taskdefname: 'TBDTBD'
    - service: 'ISL'
      servicename: 'HIG-EDM-R3U-ISL-S'
      clustername: 'HIG-EDM-R3U-ISL-Cluster'
      taskdefname: 'HIG-EDM-R3U-ISL-Cluster-TD'
    - service: 'OptimaWeb'
      servicename: 'HIG-EDM-R3U-WEB-S'
      clustername: 'HIG-EDM-R3U-WEB-Cluster'
      taskdefname: 'HIG-EDM-R3U-WEB-Cluster-TD'
    - service: 'EDMTRACKER'
      servicename: 'HIG-EDM-R3U-TRACKER-S'
      clustername: 'HIG-EDM-R3U-TRACKER-Cluster'
      taskdefname: 'HIG-EDM-R3U-TRACKER-Cluster-TD'

microservices_edm:
  services:
    - service: 'edmDbService'
      servicename: 'HIG-EDM-R3U-edb-MS'
      clustername: 'HIG-EDM-R3U-EMS-Cluster'
      taskdefname: 'HIG-EDM-R3U-EMS-Cluster-edb-TD'
    - service: 'OfflineReportsService'
      servicename: 'HIG-EDM-R3U-off-MS'
      clustername: 'HIG-EDM-R3U-EMS-Cluster'
      taskdefname: 'HIG-EDM-R3U-EMS-Cluster-off-TD'
    - service: 'DownstreamTransformationService'
      servicename: 'HIG-EDM-R3U-dfn-MS'
      clustername: 'HIG-EDM-R3U-EMS-Cluster'
      taskdefname: 'HIG-EDM-R3U-EMS-Cluster-dfn-TD'
    - service: 'PcnDcnGenerationService'
      servicename: 'HIG-EDM-R3U-pcn-MS'
      clustername: 'HIG-EDM-R3U-EMS-Cluster'
      taskdefname: 'HIG-EDM-R3U-EMS-Cluster-pcn-TD'
    - service: 'IndexService'
      servicename: 'HIG-EDM-R3U-inx-MS'
      clustername: 'HIG-EDM-R3U-EMS-Cluster'
      taskdefname: 'HIG-EDM-R3U-EMS-Cluster-inx-TD'
    - service: 'MultiService'
      servicename: 'HIG-EDM-R3U-mti-MS'
      clustername: 'HIG-EDM-R3U-EMS-Cluster'
      taskdefname: 'HIG-EDM-R3U-EMS-Cluster-mti-TD'
    - service: 'AutoBundleService'
      servicename: 'HIG-EDM-R3U-abl-MS'
      clustername: 'HIG-EDM-R3U-EMS-Cluster'
      taskdefname: 'HIG-EDM-R3U-EMS-Cluster-abl-TD'
    - service: 'Edi837svc'
      servicename: 'HIG-EDM-R3U-edi-MS'
      clustername: 'HIG-EDM-R3U-EMS-Cluster'
      taskdefname: 'HIG-EDM-R3U-EMS-Cluster-edi-TD'
    - service: 'MultiServiceOrchestrator'
      servicename: 'HIG-EDM-R3U-Mutli-ORCH'
      clustername: 'HIG-EDM-R3U-EMS-Cluster'
      taskdefname: 'HIG-EDM-R3U-EMS-Cluster-Mutli-TaskDef'
    - service: 'DownstreamTransmissionOrchestrator'
      servicename: 'HIG-EDM-R3U-DwnstrT-ORCH'
      clustername: 'HIG-EDM-R3U-EMS-Cluster'
      taskdefname: 'HIG-EDM-R3U-EMS-Cluster-DwnstrT-TaskDef'
    - service: 'DownstreamProcessOrchestrator'
      servicename: 'HIG-EDM-R3U-DwnstrP-ORCH'
      clustername: 'HIG-EDM-R3U-EMS-Cluster'
      taskdefname: 'HIG-EDM-R3U-EMS-Cluster-DwnstrP-TaskDef'
